export const CART_ACTION_TYPES = {
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  CLEAR_CART: 'ADD_ITEM_TO_CART',
};
